##########################################
#
# beam_packet_merge_from_file.yaml
#
# Configuration for reading beam packet 
# frames from files and merge packets 
# to a bigger frame.
#
# Author: Jing Luo
#
##########################################
---
type: config
log_level: debug2
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
samples_per_data_set: 49152
num_pol: 2
buffer_depth: 105
raw_frames_per_merged_frame: 6
# The size of metadata with freq ID
freq_id_metadata_size: 72

telescope:
  name: CHIMETelescope
  require_gps: true
  query_gps: true
  require_frequency_map: true
  query_frequency_map: true
  allow_default_frequency_map: false

dataset_manager:
  use_dataset_broker: false

beam_metadata_pool:
  kotekan_metadata_pool: BeamMetadata
  num_metadata_objects: 20

merged_beam_metadata_pool:
  kotekan_metadata_pool: MergedBeamMetadata
  num_metadata_objects: 20

beam_recv_buffer:
  kotekan_buffer: standard
  num_frames: 10
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

merged_buffer:
  kotekan_buffer: standard
  num_frames: 10
  metadata_pool: merged_beam_metadata_pool
  # the size of the beam metadata with frequency is 64
  frame_size: (samples_per_data_set * num_pol + freq_id_metadata_size) * raw_frames_per_merged_frame 

raw_file_read:
  base_dir: /drives/scratch/test_beam_raw
  file_name: bass_beam_data
  read0:
    kotekan_stage: rawFileRead
    file_ext: raw
    buf: beam_recv_buffer

beam_merge:
  kotekan_stage: mergeRawBuffer
  in_buf: beam_recv_buffer
  out_buf: merged_buffer

raw_file_write:
  kotekan_stage: rawFileWrite
  in_buf: merged_buffer
  base_dir: /drives/scratch/test_beam_raw
  file_name: merged_beam_data
  file_ext: raw
  exit_after_n_files: buffer_depth
