##############################################################
#
# chime_rfi.yaml
#
# CHIME config which implements all currently availiable parts
# of the CHIME RFI detection pipeline.
#
# Author: Jacob Taylor
#
##############################################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: WARN
num_links: 4
timesamples_per_packet: 2
num_elements: 2048
num_local_freq: 1
num_total_freq: 1024
samples_per_data_set: 49152
#samples_per_data_set: 32768
num_data_sets: 1
num_gpus: 4
buffer_depth: 8
#buffer_depth: 1
sizeof_float: 4
sizeof_short: 2
reorder_map: [51,50,49,48,115,114,113,112,55,54,53,52,119,118,117,116,59,58,57,56,123,122,121,120,63,62,61,60,127,126,125,124,0,1,2,3,64,65,66,67,4,5,6,7,68,69,70,71,8,9,10,11,72,73,74,75,12,13,14,15,76,77,78,79,140,141,142,143,204,205,206,207,136,137,138,139,200,201,202,203,132,133,134,135,196,197,198,199,128,129,130,131,192,193,194,195,191,190,189,188,255,254,253,252,187,186,185,184,251,250,249,248,183,182,181,180,247,246,245,244,179,178,177,176,243,242,241,240,291,290,289,288,355,354,353,352,292,293,294,295,356,357,358,359,296,297,298,299,360,361,362,363,300,301,302,303,364,365,366,367,275,274,273,272,339,338,337,336,279,278,277,276,343,342,341,340,283,282,281,280,347,346,345,344,287,286,285,284,351,350,349,348,396,397,398,399,460,461,462,463,392,393,394,395,456,457,458,459,388,389,390,391,452,453,454,455,384,385,386,387,448,449,450,451,428,429,430,431,492,493,494,495,424,425,426,427,488,489,490,491,420,421,422,423,484,485,486,487,416,417,418,419,480,481,482,483,35,34,33,32,99,98,97,96,39,38,37,36,103,102,101,100,43,42,41,40,107,106,105,104,47,46,45,44,111,110,109,108,16,17,18,19,80,81,82,83,20,21,22,23,84,85,86,87,24,25,26,27,88,89,90,91,28,29,30,31,92,93,94,95,156,157,158,159,220,221,222,223,152,153,154,155,216,217,218,219,148,149,150,151,212,213,214,215,144,145,146,147,208,209,210,211,175,174,173,172,239,238,237,236,171,170,169,168,235,234,233,232,167,166,165,164,231,230,229,228,163,162,161,160,227,226,225,224,307,306,305,304,371,370,369,368,311,310,309,308,375,374,373,372,315,314,313,312,379,378,377,376,319,318,317,316,383,382,381,380,259,258,257,256,323,322,321,320,263,262,261,260,327,326,325,324,267,266,265,264,331,330,329,328,271,270,269,268,335,334,333,332,412,413,414,415,476,477,478,479,408,409,410,411,472,473,474,475,404,405,406,407,468,469,470,471,400,401,402,403,464,465,466,467,444,445,446,447,508,509,510,511,440,441,442,443,504,505,506,507,436,437,438,439,500,501,502,503,432,433,434,435,496,497,498,499]
link_map: [0,1,2,3]

#N2 stuff
block_size: 32
num_gpu_frames: 16

#FRB stuff
downsample_time: 3
downsample_freq: 8
factor_upchan: 128
factor_upchan_out: 16
num_frb_total_beams: 1024
frb_missing_gains: [1.0,1.0]
frb_scaling: 0.05 #1.0

#RFI stuff
sk_step: 256
rfi_combined: True
frames_per_packet: 1
bad_inputs: []

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 15 * buffer_depth

# Buffers
network_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets
    metadata_pool: main_pool
    network_buffer_0:
        kotekan_buffer: standard
    network_buffer_1:
        kotekan_buffer: standard
    network_buffer_2:
        kotekan_buffer: standard
    network_buffer_3:
        kotekan_buffer: standard

beamform_output_buffers:
    num_frames: buffer_depth
    frame_size: num_data_sets * (samples_per_data_set/downsample_time/downsample_freq) * num_frb_total_beams * sizeof_float
    metadata_pool: main_pool
    beamform_output_buffer_0:
        kotekan_buffer: standard
    beamform_output_buffer_1:
        kotekan_buffer: standard
    beamform_output_buffer_2:
        kotekan_buffer: standard
    beamform_output_buffer_3:
        kotekan_buffer: standard

gpu_output_buffers:
    num_frames: buffer_depth
    frame_size: sizeof_float * num_data_sets * num_local_freq * ((num_elements * num_elements) + (num_elements * block_size))
    metadata_pool: main_pool
    gpu_output_buffer_0:
        kotekan_buffer: standard
    gpu_output_buffer_1:
        kotekan_buffer: standard
    gpu_output_buffer_2:
        kotekan_buffer: standard
    gpu_output_buffer_3:
        kotekan_buffer: standard

gpu_rfi_output_buffers:
    num_frames: buffer_depth
    frame_size: sizeof_float * num_local_freq * samples_per_data_set / sk_step
    metadata_pool: main_pool
    gpu_rfi_output_buffer_0:
        kotekan_buffer: standard
    gpu_rfi_output_buffer_1:
        kotekan_buffer: standard
    gpu_rfi_output_buffer_2:
        kotekan_buffer: standard
    gpu_rfi_output_buffer_3:
        kotekan_buffer: standard

gpu_rfi_bad_input_buffers:
    num_frames: buffer_depth
    frame_size: sizeof_float * num_elements * num_local_freq
    metadata_pool: main_pool
    gpu_rfi_bad_input_buffer_0:
        kotekan_buffer: standard
    gpu_rfi_bad_input_buffer_1:
        kotekan_buffer: standard
    gpu_rfi_bad_input_buffer_2:
        kotekan_buffer: standard
    gpu_rfi_bad_input_buffer_3:
        kotekan_buffer: standard

lost_samples_buffer:
    kotekan_buffer: standard
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_local_freq * num_data_sets
    metadata_pool: main_pool

duplicate_samples_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_local_freq * num_data_sets
    metadata_pool: main_pool
    lost_samples_buffer_0:
        kotekan_buffer: standard
    lost_samples_buffer_1:
        kotekan_buffer: standard
    lost_samples_buffer_2:
        kotekan_buffer: standard
    lost_samples_buffer_3:
        kotekan_buffer: standard

#Processes
#gen_data:
#  type: const
#  value: 255
#  test_data_gen_0:
#    kotekan_process: testDataGen
#    network_out_buf: network_buffer_0
#  test_data_gen_1:
#    kotekan_process: testDataGen
#    network_out_buf: network_buffer_1
#  test_data_gen_2:
#    kotekan_process: testDataGen
#    network_out_buf: network_buffer_2
#  test_data_gen_3:
#    kotekan_process: testDataGen
#    network_out_buf: network_buffer_3

cpu_affinity: [2,3,8,9]
dpdk:
    kotekan_process: dpdkCore
    # Format is index = lcore, value = cpu core
    lcore_cpu_map: [0,1,6,7]
    master_lcore_cpu: 2
    alignment: samples_per_data_set * num_data_sets
    # Format is index = lcore, value = array of port IDs
    # so [[0,1],[2,3]] maps lcore 0 to service ports 0 and 1,
    # and lcore 1 to service ports 2 and 3.
    lcore_port_map:
        - [0]
        - [1]
        - [2]
        - [3]
    # One handler must be given per port.
    handlers:
        - dpdk_handler: iceBoardShuffle
        - dpdk_handler: iceBoardShuffle
        - dpdk_handler: iceBoardShuffle
        - dpdk_handler: iceBoardShuffle
    out_bufs:
        - network_buffer_0
        - network_buffer_1
        - network_buffer_2
        - network_buffer_3
    lost_samples_buf: lost_samples_buffer

zero_samples:
    multiply_ls_buffer: True
    lost_samples_buf: lost_samples_buffer
    zero_0:
        kotekan_process: zeroSamples
        out_buf: network_buffer_0
        out_lost_sample_buffers:
            - lost_samples_buffer_0
    zero_1:
        kotekan_process: zeroSamples
        out_buf: network_buffer_1
        out_lost_sample_buffers:
            - lost_samples_buffer_1
    zero_2:
        kotekan_process: zeroSamples
        out_buf: network_buffer_2
        out_lost_sample_buffers:
            - lost_samples_buffer_2
    zero_3:
        kotekan_process: zeroSamples
        out_buf: network_buffer_3
        out_lost_sample_buffers:
            - lost_samples_buffer_3

gpu:
  kernel_path: "../lib/hsa/kernels/"
  gain_dir: "../../kotekan/"
  commands:
  - name: hsaInputData
  - name: hsaInputLostSamples
  - name: hsaPresumZero
  - name: hsaOutputDataZero
  - name: hsaBarrier
  - name: hsaPresumKernel
  - name: hsaRfiTimeSum
  - name: hsaRfiBadInput
  - name: hsaRfiInputSum
#  - name: hsaCorrelatorKernel
#  - name: hsaBeamformReorder
#  - name: hsaBeamformKernel
#  - name: hsaBeamformTranspose
#  - name: hsaBeamformUpchan
#  - name: hsaBeamformOutputData
  - name: hsaRfiBadInputOutput
  - name: hsaRfiOutput
  - name: hsaOutputData
  enable_delay: true
  delay_max_fraction: 0.5
  num_gpus: 4
  block_size: 32
  buffer_depth: 4
  n_intg: 24576
  frame_arrival_period: samples_per_data_set / 390625
  gpu_0:
    kotekan_process: hsaProcess
    gpu_id: 0
    in_buffers:
      network_buf: network_buffer_0
      lost_samples_buf: lost_samples_buffer_0
    out_buffers:
      output_buf: gpu_output_buffer_0
      beamform_output_buf: beamform_output_buffer_0
      rfi_bad_input_buf: gpu_rfi_bad_input_buffer_0
      rfi_output_buf: gpu_rfi_output_buffer_0
  gpu_1:
    kotekan_process: hsaProcess
    gpu_id: 1
    in_buffers:
      network_buf: network_buffer_1
      lost_samples_buf: lost_samples_buffer_1
    out_buffers:
      output_buf: gpu_output_buffer_1
      beamform_output_buf: beamform_output_buffer_1
      rfi_bad_input_buf: gpu_rfi_bad_input_buffer_1
      rfi_output_buf: gpu_rfi_output_buffer_1
  gpu_2:
    kotekan_process: hsaProcess
    gpu_id: 2
    in_buffers:
      network_buf: network_buffer_2
      lost_samples_buf: lost_samples_buffer_2
    out_buffers:
      output_buf: gpu_output_buffer_2
      beamform_output_buf: beamform_output_buffer_2
      rfi_bad_input_buf: gpu_rfi_bad_input_buffer_2
      rfi_output_buf: gpu_rfi_output_buffer_2
  gpu_3:
    kotekan_process: hsaProcess
    gpu_id: 3
    in_buffers:
      network_buf: network_buffer_3
      lost_samples_buf: lost_samples_buffer_3
    out_buffers:
      output_buf: gpu_output_buffer_3
      beamform_output_buf: beamform_output_buffer_3
      rfi_bad_input_buf: gpu_rfi_bad_input_buffer_3
      rfi_output_buf: gpu_rfi_output_buffer_3

rfi_broadcast:
  log_level: DEBUG
  total_links: 1
  destination_protocol: UDP
  destination_ip: 10.1.113.19
#  destination_ip: 10.1.13.1
#  destination_ip: 127.0.0.1
  gpu_0:
    kotekan_process: rfiBroadcast
    rfi_in: gpu_rfi_output_buffer_0
    destination_port: 41215
  gpu_1:
    kotekan_process: rfiBroadcast
    rfi_in: gpu_rfi_output_buffer_1
    destination_port: 41216
  gpu_2:
    kotekan_process: rfiBroadcast
    rfi_in: gpu_rfi_output_buffer_2
    destination_port: 41217
  gpu_3:
    kotekan_process: rfiBroadcast
    rfi_in: gpu_rfi_output_buffer_3
    destination_port: 41218

rfi_bad_input_finder:
  log_level: DEBUG
  destination_ip: 10.1.113.19
  destination_port: 41219
  bi_frames_per_packet: 10
  gpu_0:
    kotekan_process: rfiBadInputFinder
    rfi_in: gpu_rfi_bad_input_buffer_0
  gpu_1:
    kotekan_process: rfiBadInputFinder
    rfi_in: gpu_rfi_bad_input_buffer_1
  gpu_2:
    kotekan_process: rfiBadInputFinder
    rfi_in: gpu_rfi_bad_input_buffer_2
  gpu_3:
    kotekan_process: rfiBadInputFinder
    rfi_in: gpu_rfi_bad_input_buffer_3

#rfi_record:
#  total_links: 1
#  write_to: /mnt/gong/RFI
#  write_to_disk: false
#  gpu_0:
#    kotekan_process: rfiRecord
#    rfi_in: gpu_rfi_output_buffer_0
#  gpu_1:
#    kotekan_process: rfiRecord
#    rfi_in: gpu_rfi_output_buffer_1
#  gpu_2:
#    kotekan_process: rfiRecord
#    rfi_in: gpu_rfi_output_buffer_2
#  gpu_3:
#    kotekan_process: rfiRecord
#    rfi_in: gpu_rfi_output_buffer_3

#RFI Live-view Paramters
waterfallX: 1024
num_receive_threads: 4
colorscale: 0.03
waterfall_request_delay: 60
