##########################################
#
# chime_verify_n2.yaml
#
# CHIME config to exercise full GPU functionality (N2 + FRB),
# feeding in constant data and validating the N2 output
# against pre-calculated correct answers.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info
udp_packet_size: 4928
udp_frb_packet_size: 4264
udp_frb_header_size: 168
num_links: 4
freq_array: [4,7,10,16]
timesamples_per_packet: 2
timesamples_per_frb_packet: 16
num_elements: 2048
num_local_freq: 1
num_total_freq: 4
block_size: 32
samples_per_data_set: 49152
downsample_time: 3
downsample_freq: 8
factor_upchan: 128
factor_upchan_out: 16
num_beams: 4
num_frb_total_beams: 1024
num_data_sets: 1
num_gpus: 4
buffer_depth: 8
num_gpu_frames: 16
cpu_affinity: [2,3,4,5,8,9,10,11]
sizeof_float: 4
reorder_map: [32,33,34,35,40,41,42,43,48,49,50,51,56,57,58,59,96,97,98,99,104,105,106,107,112,113,114,115,120,121,122,123,67,66,65,64,75,74,73,72,83,82,81,80,91,90,89,88,3,2,1,0,11,10,9,8,19,18,17,16,27,26,25,24,152,153,154,155,144,145,146,147,136,137,138,139,128,129,130,131,216,217,218,219,208,209,210,211,200,201,202,203,192,193,194,195,251,250,249,248,243,242,241,240,235,234,233,232,227,226,225,224,187,186,185,184,179,178,177,176,171,170,169,168,163,162,161,160,355,354,353,352,363,362,361,360,371,370,369,368,379,378,377,376,291,290,289,288,299,298,297,296,307,306,305,304,315,314,313,312,259,258,257,256,264,265,266,267,272,273,274,275,280,281,282,283,323,322,321,320,331,330,329,328,339,338,337,336,347,346,345,344,408,409,410,411,400,401,402,403,392,393,394,395,384,385,386,387,472,473,474,475,464,465,466,467,456,457,458,459,448,449,450,451,440,441,442,443,432,433,434,435,424,425,426,427,416,417,418,419,504,505,506,507,496,497,498,499,488,489,490,491,480,481,482,483,36,37,38,39,44,45,46,47,52,53,54,55,60,61,62,63,100,101,102,103,108,109,110,111,116,117,118,119,124,125,126,127,71,70,69,68,79,78,77,76,87,86,85,84,95,94,93,92,7,6,5,4,15,14,13,12,23,22,21,20,31,30,29,28,156,157,158,159,148,149,150,151,140,141,142,143,132,133,134,135,220,221,222,223,212,213,214,215,204,205,206,207,196,197,198,199,255,254,253,252,247,246,245,244,239,238,237,236,231,230,229,228,191,190,189,188,183,182,181,180,175,174,173,172,167,166,165,164,359,358,357,356,367,366,365,364,375,374,373,372,383,382,381,380,295,294,293,292,303,302,301,300,311,310,309,308,319,318,317,316,263,262,261,260,268,269,270,271,276,277,278,279,284,285,286,287,327,326,325,324,335,334,333,332,343,342,341,340,351,350,349,348,412,413,414,415,404,405,406,407,396,397,398,399,388,389,390,391,476,477,478,479,468,469,470,471,460,461,462,463,452,453,454,455,444,445,446,447,436,437,438,439,428,429,430,431,420,421,422,423,508,509,510,511,500,501,502,503,492,493,494,495,484,485,486,487]
northmost_beam: 90.
ew_spacing: [-1.,0.,1.,2.]

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 45 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets
    metadata_pool: main_pool
    gpu_input_buffer_0:
        kotekan_buffer: standard
#    gpu_input_buffer_1:
#        kotekan_buffer: standard
#    gpu_input_buffer_2:
#        kotekan_buffer: standard
#    gpu_input_buffer_3:
#        kotekan_buffer: standard

frb_output_buffer:
    num_frames: buffer_depth
    frame_size: udp_frb_packet_size*8*256
    metadata_pool: main_pool
    kotekan_buffer: standard

gpu_output_buffers:
    num_frames: buffer_depth
    frame_size: 4 * num_data_sets * num_local_freq * ((num_elements * num_elements) + (num_elements * block_size))
    metadata_pool: main_pool
    gpu_output_buffer_0:
        kotekan_buffer: standard
#    gpu_output_buffer_1:
#        kotekan_buffer: standard
#    gpu_output_buffer_2:
#        kotekan_buffer: standard
#    gpu_output_buffer_3:
#        kotekan_buffer: standard

gen_data:
  type: const
  value: 153
  test_data_gen_0:
    kotekan_stage: testDataGen
    out_buf: gpu_input_buffer_0
#  test_data_gen_1:
#    kotekan_stage: testDataGen
#    out_buf: gpu_input_buffer_1
#  test_data_gen_2:
#    kotekan_stage: testDataGen
#    out_buf: gpu_input_buffer_2
#  test_data_gen_3:
#    kotekan_stage: testDataGen
#    out_buf: gpu_input_buffer_3

lost_samples_buffer:
    kotekan_buffer: standard
    num_frames: 2 * buffer_depth
    frame_size: samples_per_data_set * num_local_freq
    metadata_pool: main_pool

gen_ok:
  type: const
  value: 0
  lost_zero:
    kotekan_stage: testDataGen
    out_buf: lost_samples_buffer

gpu:
  kernel_path: "../lib/hsa/kernels/"
  gain_dir: "../../kotekan/"
  commands: &command_list
  - name: hsaInputData

  - name: hsaPresumZero
    sub_frame_index: 0
  - name: hsaPresumZero
    sub_frame_index: 1
  - name: hsaPresumZero
    sub_frame_index: 2
  - name: hsaPresumZero
    sub_frame_index: 3

  - name: hsaOutputDataZero
    sub_frame_index: 0
  - name: hsaOutputDataZero
    sub_frame_index: 1
  - name: hsaOutputDataZero
    sub_frame_index: 2
  - name: hsaOutputDataZero
    sub_frame_index: 3

  - name: hsaBarrier

#  - name: hsaBeamformReorder
#  - name: hsaBeamformKernel
#  - name: hsaBeamformTranspose
#  - name: hsaBeamformUpchan

  - name: hsaPresumKernel
    sub_frame_index: 0
  - name: hsaPresumKernel
    sub_frame_index: 1
  - name: hsaPresumKernel
    sub_frame_index: 2
  - name: hsaPresumKernel
    sub_frame_index: 3

  - name: hsaCorrelatorKernel
    sub_frame_index: 0
  - name: hsaCorrelatorKernel
    sub_frame_index: 1
  - name: hsaCorrelatorKernel
    sub_frame_index: 2
  - name: hsaCorrelatorKernel
    sub_frame_index: 3

  #Copy out queue
  - name: hsaOutputData
    sub_frame_index: 0
  - name: hsaOutputData
    sub_frame_index: 1
  - name: hsaOutputData
    sub_frame_index: 2
  - name: hsaOutputData
    sub_frame_index: 3

  link_map: [0,1,2,3]
  num_gpus: 1
  log_level: debug2
  block_size: 32
  buffer_depth: 4
  num_sub_frames: 4
  n_intg: samples_per_data_set / 2 / num_sub_frames #6144

  frame_arrival_period: samples_per_data_set / 390625
  gpu_0:
    commands: *command_list
    kotekan_stage: hsaProcess
    gpu_id: 0
    in_buffers:
      network_buf: gpu_input_buffer_0
      lost_samples_buf: lost_samples_buffer
    out_buffers:
      output_buf: gpu_output_buffer_0
#  gpu_1:
#    commands: *command_list
#    kotekan_stage: hsaProcess
#    gpu_id: 1
#    in_buffers:
#      network_buf: gpu_input_buffer_1
#      lost_samples_buf: lost_samples_buffer
#    out_buffers:
#      output_buf: gpu_output_buffer_1
#  gpu_2:
#    commands: *command_list
#    kotekan_stage: hsaProcess
#    gpu_id: 2
#    in_buffers:
#      network_buf: gpu_input_buffer_2
#      lost_samples_buf: lost_samples_buffer
#    out_buffers:
#      output_buf: gpu_output_buffer_2
#  gpu_3:
#    commands: *command_list
#    kotekan_stage: hsaProcess
#    gpu_id: 3
#    in_buffers:
#      network_buf: gpu_input_buffer_3
#      lost_samples_buf: lost_samples_buffer
#    out_buffers:
#      output_buf: gpu_output_buffer_3

#block_size: 32
#num_blocks: (num_elements/block_size)*(num_elements/block_size+1)/2
#cpu_output_buffers:
#    num_frames: buffer_depth * 4
#    frame_size: num_local_freq * num_blocks * (block_size*block_size)*2*num_data_sets * 4
#    metadata_pool: main_pool
#    cpu_output_buffer:
#        kotekan_buffer: standard
#cpu:
#  kotekan_stage: gpuSimulate
#  log_level: debug
#  network_in_buf: gpu_input_buffer_0
#  corr_out_buf: cpu_output_buffer
#check_data:
#  kotekan_stage: testDataCheckInt
#  first_buf: gpu_output_buffer_0
#  second_buf: cpu_output_buffer


check_data:
  real: [24576]
  imag: [0]
  const_data_check_0:
    kotekan_stage: constDataCheck
    in_buf: gpu_output_buffer_0


#  const_data_check_1:
#    kotekan_stage: constDataCheck
#    in_buf: gpu_output_buffer_1
#  const_data_check_2:
#    kotekan_stage: constDataCheck
#    in_buf: gpu_output_buffer_2
#  const_data_check_3:
#    kotekan_stage: constDataCheck
#    in_buf: gpu_output_buffer_3
