##########################################
#
# chime_frb.yaml
#
# CHIME config to exercise full GPU functionality (N2 + FRB),
# with FRB postprocessing and output.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: warn
num_links: 4
timesamples_per_packet: 2
num_elements: 2048
num_local_freq: 1
num_total_freq: 4
samples_per_data_set: 49152
num_data_sets: 1
num_gpus: 4
buffer_depth: 8
cpu_affinity: [2,3,8,9]
num_gpu_frames: 16
sizeof_float: 4
sizeof_short: 2
reorder_map: [32,33,34,35,40,41,42,43,48,49,50,51,56,57,58,59,96,97,98,99,104,105,106,107,112,113,114,115,120,121,122,123,67,66,65,64,75,74,73,72,83,82,81,80,91,90,89,88,3,2,1,0,11,10,9,8,19,18,17,16,27,26,25,24,152,153,154,155,144,145,146,147,136,137,138,139,128,129,130,131,216,217,218,219,208,209,210,211,200,201,202,203,192,193,194,195,251,250,249,248,243,242,241,240,235,234,233,232,227,226,225,224,187,186,185,184,179,178,177,176,171,170,169,168,163,162,161,160,355,354,353,352,363,362,361,360,371,370,369,368,379,378,377,376,291,290,289,288,299,298,297,296,307,306,305,304,315,314,313,312,259,258,257,256,264,265,266,267,272,273,274,275,280,281,282,283,323,322,321,320,331,330,329,328,339,338,337,336,347,346,345,344,408,409,410,411,400,401,402,403,392,393,394,395,384,385,386,387,472,473,474,475,464,465,466,467,456,457,458,459,448,449,450,451,440,441,442,443,432,433,434,435,424,425,426,427,416,417,418,419,504,505,506,507,496,497,498,499,488,489,490,491,480,481,482,483,36,37,38,39,44,45,46,47,52,53,54,55,60,61,62,63,100,101,102,103,108,109,110,111,116,117,118,119,124,125,126,127,71,70,69,68,79,78,77,76,87,86,85,84,95,94,93,92,7,6,5,4,15,14,13,12,23,22,21,20,31,30,29,28,156,157,158,159,148,149,150,151,140,141,142,143,132,133,134,135,220,221,222,223,212,213,214,215,204,205,206,207,196,197,198,199,255,254,253,252,247,246,245,244,239,238,237,236,231,230,229,228,191,190,189,188,183,182,181,180,175,174,173,172,167,166,165,164,359,358,357,356,367,366,365,364,375,374,373,372,383,382,381,380,295,294,293,292,303,302,301,300,311,310,309,308,319,318,317,316,263,262,261,260,268,269,270,271,276,277,278,279,284,285,286,287,327,326,325,324,335,334,333,332,343,342,341,340,351,350,349,348,412,413,414,415,404,405,406,407,396,397,398,399,388,389,390,391,476,477,478,479,468,469,470,471,460,461,462,463,452,453,454,455,444,445,446,447,436,437,438,439,428,429,430,431,420,421,422,423,508,509,510,511,500,501,502,503,492,493,494,495,484,485,486,487]
link_map: [0,1,2,3]

#N2 stuff
block_size: 32

#FRB stuff
downsample_time: 3
downsample_freq: 8
factor_upchan: 128
factor_upchan_out: 16
num_frb_total_beams: 1024
frb_missing_gains: [1.0,1.0]
frb_scaling: 0.05 #1.0

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 15 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets
    metadata_pool: main_pool
    gpu_input_buffer_0:
        kotekan_buffer: hsa
        gpu_id: 0
    gpu_input_buffer_1:
        kotekan_buffer: hsa
        gpu_id: 1
    gpu_input_buffer_2:
        kotekan_buffer: hsa
        gpu_id: 2
    gpu_input_buffer_3:
        kotekan_buffer: hsa
        gpu_id: 3

beamform_output_buffers:
    num_frames: buffer_depth
    frame_size: num_data_sets * (samples_per_data_set/downsample_time/downsample_freq) * num_frb_total_beams * sizeof_float
    metadata_pool: main_pool
    beamform_output_buffer_0:
        kotekan_buffer: hsa
        gpu_id: 0
    beamform_output_buffer_1:
        kotekan_buffer: hsa
        gpu_id: 1
    beamform_output_buffer_2:
        kotekan_buffer: hsa
        gpu_id: 2
    beamform_output_buffer_3:
        kotekan_buffer: hsa
        gpu_id: 3

gpu_output_buffers:
    num_frames: buffer_depth
    frame_size: 4 * num_data_sets * num_local_freq * ((num_elements * num_elements) + (num_elements * block_size))
    metadata_pool: main_pool
    gpu_output_buffer_0:
        kotekan_buffer: hsa
        gpu_id: 0
    gpu_output_buffer_1:
        kotekan_buffer: hsa
        gpu_id: 1
    gpu_output_buffer_2:
        kotekan_buffer: hsa
        gpu_id: 2
    gpu_output_buffer_3:
        kotekan_buffer: hsa
        gpu_id: 3

file_output_buffers:
    num_frames: buffer_depth
    frame_size: 4 * num_data_sets * num_local_freq * ((num_elements * num_elements) + (num_elements * block_size))
    metadata_pool: main_pool
    file_output_buffer_0:
        kotekan_buffer: standard
    file_output_buffer_1:
        kotekan_buffer: standard
    file_output_buffer_2:
        kotekan_buffer: standard
    file_output_buffer_3:
        kotekan_buffer: standard

dpdk:
  udp_packet_size: 4928
  kotekan_process: dpdkWrapper
  mode: shuffle4
  num_lcores: 4
  network_out_buf_0: gpu_input_buffer_0
  network_out_buf_1: gpu_input_buffer_1
  network_out_buf_2: gpu_input_buffer_2
  network_out_buf_3: gpu_input_buffer_3

gpu:
  kernel_path: "../lib/hsa/kernels/"
  commands:
  - name: hsaInputData
  - name: hsaPresumZero
  - name: hsaOutputDataZero
  - name: hsaBarrier
  - name: hsaPresumKernel
  - name: hsaCorrelatorKernel
  - name: hsaBeamformReorder
  - name: hsaBeamformKernel
  - name: hsaBeamformTranspose
  - name: hsaBeamformUpchan
  - name: hsaBeamformOutputData
  - name: hsaOutputData
  enable_delay: true
  delay_max_fraction: 0.5
  num_gpus: 4
  block_size: 32
  buffer_depth: 4
  n_intg: 24576
  frame_arrival_period: samples_per_data_set / 390625
  gpu_0:
    gain_dir: "../../kotekan/"
    ew_spacing: [0,-0.1,0.1,0.2]
    northmost_beam: 90.0
    kotekan_process: hsaProcess
    gpu_id: 0
    in_buffers:
      network_buf: gpu_input_buffer_0
    out_buffers:
      output_buf: gpu_output_buffer_0
      beamform_output_buf: beamform_output_buffer_0
  gpu_1:
    gain_dir: "../../kotekan/"
    ew_spacing: [0,-0.1,0.1,0.2]
    northmost_beam: 90.0
    kotekan_process: hsaProcess
    gpu_id: 1
    in_buffers:
      network_buf: gpu_input_buffer_1
    out_buffers:
      output_buf: gpu_output_buffer_1
      beamform_output_buf: beamform_output_buffer_1
  gpu_2:
    gain_dir: "../../kotekan/"
    ew_spacing: [0,-0.1,0.1,0.2]
    northmost_beam: 90.0
    kotekan_process: hsaProcess
    gpu_id: 2
    in_buffers:
      network_buf: gpu_input_buffer_2
    out_buffers:
      output_buf: gpu_output_buffer_2
      beamform_output_buf: beamform_output_buffer_2
  gpu_3:
    gain_dir: "../../kotekan/"
    ew_spacing: [0,-0.1,0.1,0.2]
    northmost_beam: 90.0
    kotekan_process: hsaProcess
    gpu_id: 3
    in_buffers:
      network_buf: gpu_input_buffer_3
    out_buffers:
      output_buf: gpu_output_buffer_3
      beamform_output_buf: beamform_output_buffer_3

accumulate:
    cpu_affinity: [8]
    acc_0:
        kotekan_process: accumulate
        in_buf: gpu_output_buffer_0
        out_buf: file_output_buffer_0
    acc_1:
        kotekan_process: accumulate
        in_buf: gpu_output_buffer_1
        out_buf: file_output_buffer_1
    acc_2:
        kotekan_process: accumulate
        in_buf: gpu_output_buffer_2
        out_buf: file_output_buffer_2
    acc_3:
        kotekan_process: accumulate
        in_buf: gpu_output_buffer_3
        out_buf: file_output_buffer_3


debug_plots:
    plot_0:
        kotekan_process: pyPlotN2
        in_buf: gpu_output_buffer_0
        gpu_id: 0
    plot_1:
        kotekan_process: pyPlotN2
        in_buf: gpu_output_buffer_1
        gpu_id: 1
    plot_2:
        kotekan_process: pyPlotN2
        in_buf: gpu_output_buffer_2
        gpu_id: 2
    plot_3:
        kotekan_process: pyPlotN2
        in_buf: gpu_output_buffer_3
        gpu_id: 3


frb:
  factor_upchan_out: 16
  num_beams: 4
  timesamples_per_frb_packet: 16
  frb_output_buffer:
    num_frames: buffer_depth
    frame_size: 8 * 256 * (num_beams * num_gpus * factor_upchan_out * timesamples_per_frb_packet
                           + 24 + sizeof_short * num_beams + sizeof_short * num_gpus
                                + sizeof_float * num_beams * num_gpus
                                + sizeof_float * num_beams * num_gpus)
    metadata_pool: main_pool
    kotekan_buffer: standard
  postprocess:
    log_level: info
    cpu_affinity: [11]
    kotekan_process: frbPostProcess
    incoherent_beams: [0]
    #incoherent_truncation: 25.
    network_input_buffer_0: beamform_output_buffer_0
    network_input_buffer_1: beamform_output_buffer_1
    network_input_buffer_2: beamform_output_buffer_2
    network_input_buffer_3: beamform_output_buffer_3
    frb_out_buf: frb_output_buffer
    in_buf_0: beamform_output_buffer_0
    in_buf_1: beamform_output_buffer_1
    in_buf_2: beamform_output_buffer_2
    in_buf_3: beamform_output_buffer_3
    out_buf: frb_output_buffer
  buffer_read:
    cpu_affinity: [11]
    kotekan_process: frbNetworkProcess
    in_buf: frb_output_buffer
    udp_frb_port_number: 1313
    number_of_nodes: 256
    packets_per_stream: 8
    number_of_subnets: 4
    #column_mode: true
    beam_offset: 0
    time_interval: 125829120
    L1_node_ips:
      - 10.6.200.10
      - 10.7.200.10
      - 10.6.200.11
      - 10.7.200.11
      - 10.6.200.12
      - 10.7.200.12
      - 10.6.200.13
      - 10.7.200.13
      - 10.6.200.14
      - 10.7.200.14
      - 10.6.200.15
      - 10.7.200.15
      - 10.6.200.16
      - 10.7.200.16
      - 10.6.200.17
      - 10.7.200.17
