---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: debug

buffer_depth: 12
samples_per_data_set: 32768 * 4
num_local_freq: 8
num_elements: 256
num_blocks: (num_elements / block_size) * (num_elements / block_size + 1) / 2
sizeof_int: 4
num_gpus: 1
block_size: 32
num_data_sets: 1

cpu_affinity: [8, 72, 9, 73, 10, 74, 11, 75, 12, 76, 12, 77, 13, 78, 14, 79, 15, 80]

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 128 * buffer_depth

gpu_input_merged_0:
    kotekan_buffer: standard
    num_frames: 12
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool

gpu_input_merged_1:
    kotekan_buffer: standard
    num_frames: 12
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool

gpu_input_merged_2:
    kotekan_buffer: standard
    num_frames: 12
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool

gpu_input_merged_3:
    kotekan_buffer: standard
    num_frames: 12
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool

gpu_input_merged_4:
    kotekan_buffer: standard
    num_frames: 12
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool

gpu_output_buffers:
    num_frames: buffer_depth * 4
    frame_size: num_local_freq * num_blocks * (block_size*block_size)*2*num_data_sets  * sizeof_int
    metadata_pool: main_pool
    gpu_output_buffer:
        kotekan_buffer: standard
    gpu_output_buffer_1:
        kotekan_buffer: standard

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool
    gpu_input_buffer_0:
        kotekan_buffer: standard
    gpu_input_buffer_1:
        kotekan_buffer: standard
    gpu_input_buffer_2:
        kotekan_buffer: standard
    gpu_input_buffer_3:
        kotekan_buffer: standard
    gpu_input_buffer_4:
        kotekan_buffer: standard
    gpu_input_buffer_5:
        kotekan_buffer: standard
    gpu_input_buffer_6:
        kotekan_buffer: standard
    gpu_input_buffer_7:
        kotekan_buffer: standard
    gpu_input_buffer_8:
        kotekan_buffer: standard
    gpu_input_buffer_9:
        kotekan_buffer: standard
    gpu_input_buffer_10:
        kotekan_buffer: standard
    gpu_input_buffer_11:
        kotekan_buffer: standard
    gpu_input_buffer_12:
        kotekan_buffer: standard
    gpu_input_buffer_13:
        kotekan_buffer: standard
    gpu_input_buffer_14:
        kotekan_buffer: standard
    gpu_input_buffer_15:
        kotekan_buffer: standard
    gpu_input_buffer_16:
        kotekan_buffer: standard
    gpu_input_buffer_17:
        kotekan_buffer: standard
    gpu_input_buffer_18:
        kotekan_buffer: standard
    gpu_input_buffer_19:
        kotekan_buffer: standard
    gpu_input_buffer_20:
        kotekan_buffer: standard
    gpu_input_buffer_21:
        kotekan_buffer: standard
    gpu_input_buffer_22:
        kotekan_buffer: standard
    gpu_input_buffer_23:
        kotekan_buffer: standard


lost_samples_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set
    metadata_pool: main_pool
    lost_samples_buffer_0:
        kotekan_buffer: standard
    lost_samples_buffer_1:
        kotekan_buffer: standard
    lost_samples_buffer_2:
        kotekan_buffer: standard
    lost_samples_buffer_3:
        kotekan_buffer: standard
    lost_samples_buffer_4:
        kotekan_buffer: standard
    lost_samples_buffer_5:
        kotekan_buffer: standard
    lost_samples_buffer_6:
        kotekan_buffer: standard
    lost_samples_buffer_7:
        kotekan_buffer: standard
    lost_samples_buffer_8:
        kotekan_buffer: standard
    lost_samples_buffer_9:
        kotekan_buffer: standard
    lost_samples_buffer_10:
        kotekan_buffer: standard
    lost_samples_buffer_11:
        kotekan_buffer: standard
    lost_samples_buffer_12:
        kotekan_buffer: standard
    lost_samples_buffer_13:
        kotekan_buffer: standard
    lost_samples_buffer_14:
        kotekan_buffer: standard
    lost_samples_buffer_15:
        kotekan_buffer: standard
    lost_samples_buffer_16:
        kotekan_buffer: standard
    lost_samples_buffer_17:
        kotekan_buffer: standard
    lost_samples_buffer_18:
        kotekan_buffer: standard
    lost_samples_buffer_19:
        kotekan_buffer: standard
    lost_samples_buffer_20:
        kotekan_buffer: standard
    lost_samples_buffer_21:
        kotekan_buffer: standard
    lost_samples_buffer_22:
        kotekan_buffer: standard
    lost_samples_buffer_23:
        kotekan_buffer: standard


dpdk:
    kotekan_stage: dpdkCore
    # Format is index = lcore, value = cpu core
    lcore_cpu_map: [0,64,1,65,2,66,3,67,4,68,5,69]
    master_lcore_cpu: 7
    fpga_packet_size: 4680
    alignment: samples_per_data_set
    mbuf_cache_size: 250
    # Format is index = lcore, value = array of port IDs
    # so [[0,1],[2,3]] maps lcore 0 to service ports 0 and 1,
    # and lcore 1 to service ports 2 and 3.
    lcore_port_map:
        - [0,1]
        - [2,3]
        - [4,5]
        - [6,7]
        - [8,9]
        - [10,11]
        - [12,13]
        - [14,15]
        - [16,17]
        - [18,19]
        - [20,21]
        - [22,23]

    # One handler must be given per port on the system.
    handlers:
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_0
          lost_samples_buf: lost_samples_buffer_0
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_1
          lost_samples_buf: lost_samples_buffer_1
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_2
          lost_samples_buf: lost_samples_buffer_2
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_3
          lost_samples_buf: lost_samples_buffer_3
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_4
          lost_samples_buf: lost_samples_buffer_4
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_5
          lost_samples_buf: lost_samples_buffer_5
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_6
          lost_samples_buf: lost_samples_buffer_6
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_7
          lost_samples_buf: lost_samples_buffer_7
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_8
          lost_samples_buf: lost_samples_buffer_8
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_9
          lost_samples_buf: lost_samples_buffer_9
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_10
          lost_samples_buf: lost_samples_buffer_10
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_11
          lost_samples_buf: lost_samples_buffer_11
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_12
          lost_samples_buf: lost_samples_buffer_12
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_13
          lost_samples_buf: lost_samples_buffer_13
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_14
          lost_samples_buf: lost_samples_buffer_14
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_15
          lost_samples_buf: lost_samples_buffer_15
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_16
          lost_samples_buf: lost_samples_buffer_16
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_17
          lost_samples_buf: lost_samples_buffer_17
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_18
          lost_samples_buf: lost_samples_buffer_18
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_19
          lost_samples_buf: lost_samples_buffer_19
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_20
          lost_samples_buf: lost_samples_buffer_20
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_21
          lost_samples_buf: lost_samples_buffer_21
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_22
          lost_samples_buf: lost_samples_buffer_22
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_23
          lost_samples_buf: lost_samples_buffer_23


zero_samples:
    zero_0:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_0
        lost_samples_buf: lost_samples_buffer_0
    zero_1:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_1
        lost_samples_buf: lost_samples_buffer_1
    zero_2:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_2
        lost_samples_buf: lost_samples_buffer_2
    zero_3:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_3
        lost_samples_buf: lost_samples_buffer_3
    zero_4:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_4
        lost_samples_buf: lost_samples_buffer_4
    zero_5:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_5
        lost_samples_buf: lost_samples_buffer_5
    zero_6:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_6
        lost_samples_buf: lost_samples_buffer_6
    zero_7:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_7
        lost_samples_buf: lost_samples_buffer_7
    zero_8:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_8
        lost_samples_buf: lost_samples_buffer_8
    zero_9:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_9
        lost_samples_buf: lost_samples_buffer_9
    zero_10:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_10
        lost_samples_buf: lost_samples_buffer_10
    zero_11:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_11
        lost_samples_buf: lost_samples_buffer_11
    zero_12:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_12
        lost_samples_buf: lost_samples_buffer_12
    zero_13:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_13
        lost_samples_buf: lost_samples_buffer_13
    zero_14:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_14
        lost_samples_buf: lost_samples_buffer_14
    zero_15:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_15
        lost_samples_buf: lost_samples_buffer_15
    zero_16:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_16
        lost_samples_buf: lost_samples_buffer_16
    zero_17:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_17
        lost_samples_buf: lost_samples_buffer_17
    zero_18:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_18
        lost_samples_buf: lost_samples_buffer_18
    zero_19:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_19
        lost_samples_buf: lost_samples_buffer_19
    zero_20:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_20
        lost_samples_buf: lost_samples_buffer_20
    zero_21:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_21
        lost_samples_buf: lost_samples_buffer_21
    zero_22:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_22
        lost_samples_buf: lost_samples_buffer_22
    zero_23:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_23
        lost_samples_buf: lost_samples_buffer_23

# This seems to find the lockup condition
#monitor:
#    kotekan_stage: monitorBuffer
#    bufs:
#        - gpu_input_buffer_0
#        - lost_samples_buffer_0
#    timeout: 10
#    fill_threshold: 0.80

buffer_merge_0:
    kotekan_stage: bufferMerge
    in_bufs:
        - gpu_input_buffer_0
        - gpu_input_buffer_1
        - gpu_input_buffer_2
        - gpu_input_buffer_3
        - gpu_input_buffer_4
        - gpu_input_buffer_5
        - gpu_input_buffer_6
        - gpu_input_buffer_7
#        - gpu_input_buffer_8
#        - gpu_input_buffer_9
#        - gpu_input_buffer_10
#        - gpu_input_buffer_11
#        - gpu_input_buffer_12
#        - gpu_input_buffer_13
#        - gpu_input_buffer_14
#        - gpu_input_buffer_15
    out_buf: gpu_input_merged_0

buffer_merge_1:
    kotekan_stage: bufferMerge
    in_bufs:
            - gpu_input_buffer_8
            - gpu_input_buffer_9
            - gpu_input_buffer_10
            - gpu_input_buffer_11
            - gpu_input_buffer_12
            - gpu_input_buffer_13
            - gpu_input_buffer_14
            - gpu_input_buffer_15
    out_buf: gpu_input_merged_1

copy_compress_lost_samples_buffers:
    kotekan_stage: bufferCopy
    in_buf: gpu_input_merged_0
    out_bufs:
        - gpu_input_merged_2

copy_compress_lost_samples_buffers_1:
    kotekan_stage: bufferCopy
    in_buf: gpu_input_merged_1
    out_bufs:
        - gpu_input_merged_3

buffer_merge_2:
    kotekan_stage: bufferMerge
    in_bufs:
        - gpu_input_merged_2
        - gpu_input_merged_3
    out_buf: gpu_input_merged_4

#
#buffer_merge_1:
#    kotekan_stage: bufferMerge
#    in_bufs:
#        - gpu_input_buffer_8
#        - gpu_input_buffer_9
#        - gpu_input_buffer_10
#        - gpu_input_buffer_11
##        - gpu_input_buffer_12
##        - gpu_input_buffer_13
##        - gpu_input_buffer_14
##        - gpu_input_buffer_15
#    out_buf: gpu_input_merged_1


#gen_data:
#    type: const
#    value: 153
#    kotekan_stage: testDataGen
#    out_buf: gpu_input_merged
#    wait: true

#gen_data_0:
#    type: const
#    value: 153
#    kotekan_stage: testDataGen
#    out_buf: gpu_input_merged_1
#    wait: false

#gpu:
#    profiling: true
#    frame_arrival_period: samples_per_data_set / 390625.0 / 12
#    commands:
#        - name: cudaInputData
##        - name: cudaCorrelatorKernel
#        - name: cudaOutputData
#    gpu_0:
#        kotekan_stage: cudaProcess
#        gpu_id: 0
#        in_buffers:
#            in_buf: gpu_input_merged
#        out_buffers:
#            output_buf: gpu_output_buffer

num_sub_frames: 1

gpu:
    profiling: true
    kernel_path: "../lib/hsa/kernels/"
    gain_dir: "/etc/kotekan/"
    #log_level: debug2
    data_format: "4+4b"
    frame_arrival_period: samples_per_data_set / 390625.0 / 8
    commands:
        - name: hsaInputData
        #- name: clPresumZero
        #- name: clOutputDataZero
        #- name: hsaBarrier
        #- name: hsaPresumKernel
        #  - name: clPreseedKernel
        #  - name: clCorrelatorKernel
        # - name: clKVCorr
        # - name: hsaOutputData
    gpu_0:
        kotekan_stage: hsaProcess
        buffer_depth: 4
        cpu_affinity: [16,17,18,19]
        gpu_id: 0
        gpu_thread_id: 0
        in_buffers:
            network_buf: gpu_input_merged_4
        out_buffers:
            output_buf: gpu_output_buffer

#gpu:
#    profiling: false
#    kernel_path: "../../lib/opencl/kernels/"
#    gain_dir: "/etc/kotekan/"
#    #log_level: debug2
#    data_format: "4+4b"
#    frame_arrival_period: samples_per_data_set / 390625.0 / 16
#    commands:
#        - name: clInputData
#        #- name: clPresumZero
#        #- name: clOutputDataZero
#        - name: clPresumKernel
#        #  - name: clPreseedKernel
#        #  - name: clCorrelatorKernel
#        # - name: clKVCorr
#        - name: clOutputData
#    gpu_0:
#        kotekan_stage: clProcess
#        cpu_affinity: [16,17,18,19]
#        gpu_id: 0
#        gpu_thread_id: 0
#        in_buffers:
#            network_buf: gpu_input_merged
#        out_buffers:
#            output_buf: gpu_output_buffer
#    gpu_1:
#        kotekan_stage: clProcess
#        cpu_affinity: [20,21,22,23]
#        gpu_id: 0
#        gpu_thread_id: 1
#        in_buffers:
#            network_buf: gpu_input_merged_1
#        out_buffers:
#            output_buf: gpu_output_buffer_1
