---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: debug

buffer_depth: 8
samples_per_data_set: 49152
num_elements: 16
num_local_freq: 128

cpu_affinity: [0, 16, 1, 17, 10, 26, 11, 27, 14, 30, 15, 31]

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 128 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool
    gpu_input_buffer_0:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_1:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_2:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_3:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_4:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_5:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_6:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_7:
        kotekan_buffer: standard
        numa_node: 0
    gpu_input_buffer_8:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_9:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_10:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_11:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_12:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_13:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_14:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_15:
        kotekan_buffer: standard
        numa_node: 1
    gpu_input_buffer_16:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_17:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_18:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_19:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_20:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_21:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_22:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_23:
        kotekan_buffer: standard
        numa_node: 2
    gpu_input_buffer_24:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_25:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_26:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_27:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_28:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_29:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_30:
        kotekan_buffer: standard
        numa_node: 3
    gpu_input_buffer_31:
        kotekan_buffer: standard
        numa_node: 3


lost_samples_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set
    metadata_pool: main_pool
    lost_samples_buffer_0:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_1:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_2:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_3:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_4:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_5:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_6:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_7:
        kotekan_buffer: standard
        numa_node: 0
    lost_samples_buffer_8:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_9:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_10:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_11:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_12:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_13:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_14:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_15:
        kotekan_buffer: standard
        numa_node: 1
    lost_samples_buffer_16:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_17:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_18:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_19:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_20:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_21:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_22:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_23:
        kotekan_buffer: standard
        numa_node: 2
    lost_samples_buffer_24:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_25:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_26:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_27:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_28:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_29:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_30:
        kotekan_buffer: standard
        numa_node: 3
    lost_samples_buffer_31:
        kotekan_buffer: standard
        numa_node: 3

dpdk:
    kotekan_stage: dpdkCore
    # Format is index = lcore, value = cpu core
    lcore_cpu_map: [2, 18, 3, 19, 4, 20, 5, 21, 8, 24, 9, 25, 12, 28, 13, 29]
    master_lcore_cpu: 2
    fpga_packet_size: 4680
    alignment: samples_per_data_set
    # Format is index = lcore, value = array of port IDs
    # so [[0,1],[2,3]] maps lcore 0 to service ports 0 and 1,
    # and lcore 1 to service ports 2 and 3.
    lcore_port_map:
        - [0,1]
        - [2,3]
        - [4,5]
        - [6,7]
        - [8,9]
        - [10,11]
        - [12,13]
        - [14,15]
        - [16,17]
        - [18,19]
        - [20,21]
        - [22,23]
        - [24,25]
        - [26,27]
        - [28,29]
        - [30,31]
    # One handler must be given per port on the system.
    handlers:
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_0
          lost_samples_buf: lost_samples_buffer_0
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_1
          lost_samples_buf: lost_samples_buffer_1
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_2
          lost_samples_buf: lost_samples_buffer_2
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_3
          lost_samples_buf: lost_samples_buffer_3
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_4
          lost_samples_buf: lost_samples_buffer_4
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_5
          lost_samples_buf: lost_samples_buffer_5
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_6
          lost_samples_buf: lost_samples_buffer_6
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_7
          lost_samples_buf: lost_samples_buffer_7
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_8
          lost_samples_buf: lost_samples_buffer_8
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_9
          lost_samples_buf: lost_samples_buffer_9
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_10
          lost_samples_buf: lost_samples_buffer_10
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_11
          lost_samples_buf: lost_samples_buffer_11
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_12
          lost_samples_buf: lost_samples_buffer_12
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_13
          lost_samples_buf: lost_samples_buffer_13
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_14
          lost_samples_buf: lost_samples_buffer_14
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_15
          lost_samples_buf: lost_samples_buffer_15
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_16
          lost_samples_buf: lost_samples_buffer_16
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_17
          lost_samples_buf: lost_samples_buffer_17
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_18
          lost_samples_buf: lost_samples_buffer_18
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_19
          lost_samples_buf: lost_samples_buffer_19
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_20
          lost_samples_buf: lost_samples_buffer_20
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_21
          lost_samples_buf: lost_samples_buffer_21
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_22
          lost_samples_buf: lost_samples_buffer_22
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_23
          lost_samples_buf: lost_samples_buffer_23
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_24
          lost_samples_buf: lost_samples_buffer_24
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_25
          lost_samples_buf: lost_samples_buffer_25
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_26
          lost_samples_buf: lost_samples_buffer_26
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_27
          lost_samples_buf: lost_samples_buffer_27
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_28
          lost_samples_buf: lost_samples_buffer_28
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_29
          lost_samples_buf: lost_samples_buffer_29
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_30
          lost_samples_buf: lost_samples_buffer_30
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_31
          lost_samples_buf: lost_samples_buffer_31

zero_samples:
    zero_0:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_0
        lost_samples_buf: lost_samples_buffer_0
    zero_1:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_1
        lost_samples_buf: lost_samples_buffer_1
    zero_2:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_2
        lost_samples_buf: lost_samples_buffer_2
    zero_3:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_3
        lost_samples_buf: lost_samples_buffer_3
    zero_4:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_4
        lost_samples_buf: lost_samples_buffer_4
    zero_5:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_5
        lost_samples_buf: lost_samples_buffer_5
    zero_6:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_6
        lost_samples_buf: lost_samples_buffer_6
    zero_7:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_7
        lost_samples_buf: lost_samples_buffer_7
    zero_8:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_8
        lost_samples_buf: lost_samples_buffer_8
    zero_9:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_9
        lost_samples_buf: lost_samples_buffer_9
    zero_10:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_10
        lost_samples_buf: lost_samples_buffer_10
    zero_11:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_11
        lost_samples_buf: lost_samples_buffer_11
    zero_12:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_12
        lost_samples_buf: lost_samples_buffer_12
    zero_13:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_13
        lost_samples_buf: lost_samples_buffer_13
    zero_14:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_14
        lost_samples_buf: lost_samples_buffer_14
    zero_15:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_15
        lost_samples_buf: lost_samples_buffer_15
    zero_16:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_16
        lost_samples_buf: lost_samples_buffer_16
    zero_17:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_17
        lost_samples_buf: lost_samples_buffer_17
    zero_18:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_18
        lost_samples_buf: lost_samples_buffer_18
    zero_19:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_19
        lost_samples_buf: lost_samples_buffer_19
    zero_20:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_20
        lost_samples_buf: lost_samples_buffer_20
    zero_21:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_21
        lost_samples_buf: lost_samples_buffer_21
    zero_22:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_22
        lost_samples_buf: lost_samples_buffer_22
    zero_23:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_23
        lost_samples_buf: lost_samples_buffer_23
    zero_24:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_24
        lost_samples_buf: lost_samples_buffer_24
    zero_25:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_25
        lost_samples_buf: lost_samples_buffer_25
    zero_26:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_26
        lost_samples_buf: lost_samples_buffer_26
    zero_27:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_27
        lost_samples_buf: lost_samples_buffer_27
    zero_28:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_28
        lost_samples_buf: lost_samples_buffer_28
    zero_29:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_29
        lost_samples_buf: lost_samples_buffer_29
    zero_30:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_30
        lost_samples_buf: lost_samples_buffer_30
    zero_31:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_31
        lost_samples_buf: lost_samples_buffer_31

metadata:
    metadata_0:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_0
    metadata_1:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_1
    metadata_2:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_2
    metadata_3:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_3
    metadata_4:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_4
    metadata_5:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_5
    metadata_6:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_6
    metadata_7:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_7
    metadata_8:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_8
    metadata_9:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_9
    metadata_10:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_10
    metadata_11:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_11
    metadata_12:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_12
    metadata_13:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_13
    metadata_14:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_14
    metadata_15:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_15
    metadata_16:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_16
    metadata_17:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_17
    metadata_18:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_18
    metadata_19:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_19
    metadata_20:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_20
    metadata_21:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_21
    metadata_22:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_22
    metadata_23:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_23
    metadata_24:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_24
    metadata_25:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_25
    metadata_26:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_26
    metadata_27:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_27
    metadata_28:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_28
    metadata_29:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_29
    metadata_30:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_30
    metadata_31:
        kotekan_stage: chimeMetadataDump
        in_buf: gpu_input_buffer_31

#hex_dump:
#    kotekan_stage: hexDump:
#    buf: gpu_input_buffer_0