##########################################
#
# verify_opencl.yaml
#
# Config to test the opencl stack.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info
num_links: 4
freq_array: [4,7,10,16]
timesamples_per_packet: 2
block_size: 32
samples_per_data_set: 49152 #16384
num_beams: 1
num_data_sets: 1
num_gpus: 1
buffer_depth: 4
num_gpu_frames: 16
cpu_affinity: [2,3,4,5,8,9,10,11]
sizeof_float: 4
num_elements: 256 #2048
num_local_freq: 1
num_blocks: (num_elements / block_size) * (num_elements / block_size + 1) / 2
sizeof_int: 4

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 15 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets
    metadata_pool: main_pool
    gpu_input_buffer:
        kotekan_buffer: standard

gpu_output_buffers:
    num_frames: buffer_depth * 4
    frame_size: num_local_freq * num_blocks * (block_size*block_size)*2*num_data_sets  * sizeof_int
    metadata_pool: main_pool
    gpu_output_buffer:
        kotekan_buffer: standard

cpu_output_buffers:
    num_frames: buffer_depth * 4
    frame_size: num_local_freq * num_blocks * (block_size*block_size)*2*num_data_sets  * sizeof_int
    metadata_pool: main_pool
    cpu_output_buffer:
        kotekan_buffer: standard

beamform_output_buffers:
    frame_size: samples_per_data_set * num_data_sets * num_local_freq * 2
    metadata_pool: main_pool
    beamform_output_buffer:
        kotekan_buffer: standard
        num_frames: buffer_depth

gen_data:
  type: random #const
  value: 153
  kotekan_stage: testDataGen
  out_buf: gpu_input_buffer

#data_format: dot4b
data_format: "4+4b"
#full_complicated: false #don't use the ISA-like kernel: intrinsics, extra packing, overflows, etc

gpu:
  profiling: true
  kernel_path: "/var/lib/kotekan/opencl/kernels/"
  gain_dir: "/etc/kotekan/"
  log_level: debug2
  buffer_depth: 3
  frame_arrival_period: 390625
  commands: &command_list
  - name: clInputData
    gpu_memory: input
    in_bufs:
      - network_buf
  - name: clPresumZero
  - name: clOutputDataZero
  - name: clPresumKernel
  - name: clPreseedKernel
  - name: clCorrelatorKernel
#  - name: clKVCorr
  - name: clOutputData
    out_bufs:
      - output_buf
    in_bufs:
      - network_buf
  gpu_0:
    kotekan_stage: clProcess
    gpu_id: 0
    commands: *command_list
    in_buffers:
      network_buf: gpu_input_buffer
    out_buffers:
      output_buf: gpu_output_buffer

cpu:
  kotekan_stage: gpuSimulate
  log_level: debug
  network_in_buf: gpu_input_buffer
  corr_out_buf: cpu_output_buffer

check_data:
  kotekan_stage: testDataCheckInt
  first_buf: gpu_output_buffer
  second_buf: cpu_output_buffer

#check_data:
#  imag: [0]
#  real: [98304] #[4816896] #98 * samples_per_dataset
#  const_data_check:
#    kotekan_stage: constDataCheck
#    in_buf: gpu_output_buffer
