##########################################
#
# tracking_beam_frame_to_ndisk.yaml
#
# Configuration for recording the tracking
# beam to n disks.
#
# Author: Jing Luo
#
##########################################
---
type: config
log_level: info
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
samples_per_data_set: 49152
num_pol: 2
buffer_depth: 105
sub_frames_per_merged_frame: 500
# The size of metadata with freq ID
freq_id_metadata_size: 72

telescope:
  name: CHIMETelescope
  require_gps: true
  query_gps: true
  require_frequency_map: true
  query_frequency_map: true
  allow_default_frequency_map: false

dataset_manager:
  use_dataset_broker: false

beam_metadata_pool:
  kotekan_metadata_pool: BeamMetadata
  num_metadata_objects: 4096

merged_beam_metadata_pool:
  kotekan_metadata_pool: MergedBeamMetadata
  num_metadata_objects: 60

beam_recv_buffer:
  kotekan_buffer: standard
  num_frames: 2048
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

merged_buffer:
  kotekan_buffer: standard
  num_frames: 30
  metadata_pool: merged_beam_metadata_pool
  # freq_id_metadata_size is definded on the top
  frame_size: (samples_per_data_set * num_pol + freq_id_metadata_size) * sub_frames_per_merged_frame 

recv:
  kotekan_stage: bufferRecv
  buf: beam_recv_buffer
  #listen_port: 12020
  listen_port: 11030
  num_threads: 2

beam_merge:
  kotekan_stage: mergeBeamBuffer
  in_buf: beam_recv_buffer
  out_buf: merged_buffer

raw_capture:
   kotekan_stage: nDiskFileWrite
#################################
# THIS IS THE PLACE TO EDIT!!!  #
#################################
   note: bass test
#Change this if you want to record
   file_ext: raw
   write_to_disk: True
   write_metadata_and_gains: False
   print_lost_sample_number: False
   gain_files: Null
   num_disks: 8
   disk_base: /drives
   disk_set: CHA
   in_buf: merged_buffer

